import { defineTranslations } from "./i18n";

export const APP_STATUS_COPY = defineTranslations({
  zh: { current: (label: string) => `当前筛选：${label}`, prompt: "选择任一全景节点，下方日程将同步筛选。" },
  en: { current: (label: string) => `Current filter: ${label}`, prompt: "Select any landscape node to filter the schedule below." },
  ja: { current: (label: string) => `現在の絞り込み：${label}`, prompt: "全景の項目を選ぶと、下の日程も絞り込まれます。" },
  ko: { current: (label: string) => `현재 필터: ${label}`, prompt: "전체 보기에서 항목을 선택하면 아래 일정도 필터링됩니다." },
  fr: { current: (label: string) => `Filtre actuel : ${label}`, prompt: "Sélectionnez un élément du panorama pour filtrer le programme." },
  de: { current: (label: string) => `Aktueller Filter: ${label}`, prompt: "Wählen Sie ein Element aus, um das Programm unten zu filtern." },
  es: { current: (label: string) => `Filtro actual: ${label}`, prompt: "Selecciona un elemento del panorama para filtrar el programa." },
  ar: { current: (label: string) => `عامل التصفية الحالي: ${label}`, prompt: "اختر عنصراً من المشهد لتصفية الجدول أدناه." },
});

export const LANDSCAPE_COPY = defineTranslations({
  zh: {
    heading: "先看哪里机会最密集", intro: "从时间、主题、场馆三个维度先缩小选择，再进入完整日程。", heatTitle: "时间热力", heatIntro: "四天按半小时查看同时进行的活动数。", activeWindows: (n: number) => `${n} 个活跃时段`, eventPeak: (n: number) => `${n} 场峰值`, events: (n: number) => `${n} 场活动`, heatSummary: (date: string, start: string, end: string, n: number) => `文字摘要：${date} ${start}-${end} 为全程峰值，同时进行 ${n} 场活动。颜色越深代表同一时段选择越多，每格仍标注具体场数。`, noWindows: "文字摘要：当前没有可显示的活动时段。", topicTitle: "主题星群", topicIntro: "面积随真实活动数量变化，点击即可聚焦主题。", topicStats: "13 个真实主题类别，共 175 场", topicSummary: "文字摘要：综合论坛 45 场，大模型与AI基础 35 场，产业与工业智能化 32 场，算力与AI芯片 22 场，其余 9 类共 41 场。", venueTitle: "场馆星座", venueIntro: "位置为场馆类别关系示意，不代表精确地图坐标。", venueStats: "7 类场馆，共 175 场", schematic: "示意位置", venueSummary: "文字摘要：世博中心 91 场，世博展览馆 28 场，西岸国际会展中心 25 场，酒店、张江与其他场馆共 31 场。",
  },
  en: {
    heading: "See where opportunity concentrates", intro: "Narrow the program by time, topic, and venue before reviewing the schedule.", heatTitle: "Time heatmap", heatIntro: "Concurrent events across four days in half-hour windows.", activeWindows: (n: number) => `${n} active half-hour windows`, eventPeak: (n: number) => `${n} event peak`, events: (n: number) => `${n} ${n === 1 ? "event" : "events"}`, heatSummary: (date: string, start: string, end: string, n: number) => `Text summary: ${date} at ${start}-${end} is the overall peak with ${n} concurrent events. Darker cells mean more choices, and every cell includes its count.`, noWindows: "Text summary: no event windows are available.", topicTitle: "Topic atlas", topicIntro: "Area follows real event counts. Select a topic to focus.", topicStats: "13 real topic categories, 175 events", topicSummary: "Text summary: Comprehensive Forums 45, Foundation Models & AI 35, Industrial AI 32, Compute & AI Chips 22, and the remaining nine topics 41.", venueTitle: "Venue constellation", venueIntro: "Positions show venue-category relationships, not precise map coordinates.", venueStats: "7 venue categories, 175 events", schematic: "schematic position", venueSummary: "Text summary: Expo Center 91, Expo Exhibition and Convention Center 28, West Bund 25, and hotels, Zhangjiang, and other venues 31.",
  },
  ja: {
    heading: "機会が集中する場所を見つける", intro: "時間、テーマ、会場の3つの視点で候補を絞ってから、全日程を確認できます。", heatTitle: "時間ヒートマップ", heatIntro: "4日間の同時開催数を30分単位で表示します。", activeWindows: (n: number) => `${n}の有効時間帯`, eventPeak: (n: number) => `ピーク${n}件`, events: (n: number) => `${n}件`, heatSummary: (date: string, start: string, end: string, n: number) => `概要：${date} ${start}-${end}が全期間のピークで、${n}件が同時開催されます。色が濃いほど選択肢が多くなります。`, noWindows: "概要：表示できる時間帯はありません。", topicTitle: "テーマ星群", topicIntro: "面積は実際の件数に比例します。選択してテーマを絞り込めます。", topicStats: "13の実テーマ、全175件", topicSummary: "概要：総合45件、基盤モデル・AI 35件、産業・製造AI 32件、AIコンピューティング・チップ22件、その他9テーマ41件。", venueTitle: "会場星座", venueIntro: "配置は会場カテゴリーの関係を示すもので、正確な地図座標ではありません。", venueStats: "7会場カテゴリー、全175件", schematic: "概略位置", venueSummary: "概要：上海世博センター91件、上海世博展覧館28件、西岸国際会展センター25件、ホテル・張江・その他31件。",
  },
  ko: {
    heading: "기회가 집중되는 곳 찾기", intro: "시간, 주제, 장소의 세 가지 기준으로 먼저 좁힌 뒤 전체 일정을 확인하세요.", heatTitle: "시간 히트맵", heatIntro: "4일 동안 동시에 열리는 행사를 30분 단위로 표시합니다.", activeWindows: (n: number) => `${n}개 활성 시간대`, eventPeak: (n: number) => `최대 ${n}개`, events: (n: number) => `${n}개 행사`, heatSummary: (date: string, start: string, end: string, n: number) => `요약: ${date} ${start}-${end}에 ${n}개 행사가 동시에 열려 전체 최고치입니다. 색이 진할수록 선택지가 많습니다.`, noWindows: "요약: 표시할 행사 시간대가 없습니다.", topicTitle: "주제 성군", topicIntro: "면적은 실제 행사 수에 비례합니다. 주제를 선택해 집중하세요.", topicStats: "실제 주제 13개, 총 175개 행사", topicSummary: "요약: 종합 45개, 파운데이션 모델·AI 35개, 산업·제조 AI 32개, AI 컴퓨팅·칩 22개, 나머지 9개 주제 41개.", venueTitle: "장소 별자리", venueIntro: "배치는 장소 유형의 관계를 나타내며 정확한 지도 좌표가 아닙니다.", venueStats: "장소 유형 7개, 총 175개 행사", schematic: "개략 위치", venueSummary: "요약: 상하이 엑스포 센터 91개, 세계박람회 전시컨벤션센터 28개, 웨스트번드 25개, 호텔·장장·기타 31개.",
  },
  fr: {
    heading: "Repérez où se concentrent les opportunités", intro: "Affinez d’abord par horaire, thème et lieu, puis consultez le programme complet.", heatTitle: "Carte thermique des horaires", heatIntro: "Nombre d’événements simultanés par tranche de 30 minutes sur quatre jours.", activeWindows: (n: number) => `${n} créneaux actifs`, eventPeak: (n: number) => `Pic de ${n}`, events: (n: number) => `${n} événement${n > 1 ? "s" : ""}`, heatSummary: (date: string, start: string, end: string, n: number) => `Résumé : le pic se situe le ${date}, de ${start} à ${end}, avec ${n} événements simultanés. Une couleur plus foncée indique davantage de choix.`, noWindows: "Résumé : aucun créneau disponible.", topicTitle: "Constellation des thèmes", topicIntro: "La surface suit le nombre réel d’événements. Sélectionnez un thème pour l’isoler.", topicStats: "13 thèmes réels, 175 événements", topicSummary: "Résumé : forums généraux 45, modèles fondamentaux et IA 35, IA industrielle 32, calcul et puces IA 22, neuf autres thèmes 41.", venueTitle: "Constellation des lieux", venueIntro: "Les positions représentent les relations entre catégories, pas des coordonnées exactes.", venueStats: "7 catégories de lieux, 175 événements", schematic: "position schématique", venueSummary: "Résumé : Centre Expo 91, Centre d’exposition 28, West Bund 25, hôtels, Zhangjiang et autres lieux 31.",
  },
  de: {
    heading: "Finden Sie die dichtesten Chancen", intro: "Grenzen Sie das Programm zuerst nach Zeit, Thema und Ort ein.", heatTitle: "Zeit-Heatmap", heatIntro: "Gleichzeitige Veranstaltungen an vier Tagen in 30-Minuten-Fenstern.", activeWindows: (n: number) => `${n} aktive Zeitfenster`, eventPeak: (n: number) => `Spitze: ${n}`, events: (n: number) => `${n} Veranstaltungen`, heatSummary: (date: string, start: string, end: string, n: number) => `Zusammenfassung: Am ${date} von ${start} bis ${end} liegt die Spitze mit ${n} gleichzeitigen Veranstaltungen. Dunklere Felder bedeuten mehr Auswahl.`, noWindows: "Zusammenfassung: Keine Zeitfenster verfügbar.", topicTitle: "Themenkonstellation", topicIntro: "Die Fläche folgt der tatsächlichen Anzahl. Wählen Sie ein Thema zum Fokussieren.", topicStats: "13 echte Themen, 175 Veranstaltungen", topicSummary: "Zusammenfassung: Übergreifend 45, Basismodelle und KI 35, industrielle KI 32, KI-Computing und Chips 22, übrige neun Themen 41.", venueTitle: "Ortskonstellation", venueIntro: "Die Positionen zeigen Kategorienbeziehungen, keine genauen Kartenkoordinaten.", venueStats: "7 Ortskategorien, 175 Veranstaltungen", schematic: "schematische Position", venueSummary: "Zusammenfassung: Expo Center 91, Expo Exhibition Center 28, West Bund 25, Hotels, Zhangjiang und weitere Orte 31.",
  },
  es: {
    heading: "Descubre dónde se concentran las oportunidades", intro: "Acota primero por hora, tema y recinto y luego revisa el programa completo.", heatTitle: "Mapa de calor horario", heatIntro: "Actividades simultáneas durante cuatro días en intervalos de 30 minutos.", activeWindows: (n: number) => `${n} franjas activas`, eventPeak: (n: number) => `Pico de ${n}`, events: (n: number) => `${n} actividades`, heatSummary: (date: string, start: string, end: string, n: number) => `Resumen: el pico es el ${date} de ${start} a ${end}, con ${n} actividades simultáneas. Los tonos más oscuros indican más opciones.`, noWindows: "Resumen: no hay franjas disponibles.", topicTitle: "Constelación temática", topicIntro: "El área sigue el número real de actividades. Selecciona un tema para enfocarlo.", topicStats: "13 temas reales, 175 actividades", topicSummary: "Resumen: foros generales 45, modelos fundacionales e IA 35, IA industrial 32, computación y chips 22, otros nueve temas 41.", venueTitle: "Constelación de recintos", venueIntro: "Las posiciones muestran relaciones entre categorías, no coordenadas exactas.", venueStats: "7 categorías de recintos, 175 actividades", schematic: "posición esquemática", venueSummary: "Resumen: Centro Expo 91, Centro de Exposiciones 28, West Bund 25, hoteles, Zhangjiang y otros 31.",
  },
  ar: {
    heading: "اكتشف أين تتركز الفرص", intro: "ضيّق الخيارات حسب الوقت والموضوع والمكان قبل مراجعة الجدول الكامل.", heatTitle: "الخريطة الحرارية للوقت", heatIntro: "عدد الفعاليات المتزامنة خلال أربعة أيام بفواصل 30 دقيقة.", activeWindows: (n: number) => `${n} فترة نشطة`, eventPeak: (n: number) => `الذروة ${n}`, events: (n: number) => `${n} فعالية`, heatSummary: (date: string, start: string, end: string, n: number) => `ملخص: الذروة في ${date} من ${start} إلى ${end} مع ${n} فعالية متزامنة. اللون الأغمق يعني خيارات أكثر.`, noWindows: "ملخص: لا توجد فترات متاحة.", topicTitle: "كوكبة الموضوعات", topicIntro: "تتناسب المساحة مع العدد الفعلي. اختر موضوعاً للتركيز عليه.", topicStats: "13 موضوعاً فعلياً، 175 فعالية", topicSummary: "ملخص: المنتديات العامة 45، النماذج الأساسية 35، الذكاء الصناعي 32، الحوسبة والرقائق 22، وتسعة موضوعات أخرى 41.", venueTitle: "كوكبة الأماكن", venueIntro: "توضح المواقع العلاقة بين فئات الأماكن ولا تمثل إحداثيات دقيقة.", venueStats: "7 فئات أماكن، 175 فعالية", schematic: "موقع تقريبي", venueSummary: "ملخص: مركز شنغهاي إكسبو 91، مركز المعارض 28، ويست بوند 25، والفنادق وتشانغجيانغ وأماكن أخرى 31.",
  },
});

export const PLANNER_AUX_COPY = defineTranslations({
  zh: { hour: (n: number) => `${n} 小时`, attention: "路线注意力预算", metricLabels: ["活动场数", "有效内容小时", "目标赛道覆盖", "主题数", "换馆次数", "建议缓冲"], metricValues: [(n: number) => `${n} 场`, (n: number) => `${n} 类`, (n: number) => `${n} 次`, (n: number) => `${n} 分钟`], notSet: "未设置", reasonsLabel: "推荐理由", reasons: { interest: "直接匹配兴趣", identity: "适合你的身份", goal: "匹配参访目标", diversity: "增加主题广度", manual: "手动保留活动" }, buffer: (n: number) => `衔接提示：建议缓冲 ${n} 分钟`, shareText: "这是我的 WAIC 2026 参访路线。", shareOpened: "已打开系统分享", copied: "链接已复制", copyUnavailable: "无法复制，请从地址栏分享", cancelled: "已取消分享", shareFailed: "分享失败，请重试", icsCreated: "ICS 已生成", shareRoute: "分享路线", downloadIcs: "下载 ICS", startTime: (date: string) => `${date}开始时间`, endTime: (date: string) => `${date}结束时间`, rejections: { "outside-availability": "不在可用时段", "time-conflict": "时间冲突", "venue-buffer": "换馆缓冲不足", "daily-limit": "活动上限", "lower-match": "由匹配度更高的组合替代" }, removeFromRoute: "从路线移除" },
  en: { hour: (n: number) => `${n} hr`, attention: "Route attention budget", metricLabels: ["Events", "Content hours", "Goal-track coverage", "Topics", "Venue changes", "Suggested buffer"], metricValues: [(n: number) => String(n), (n: number) => String(n), (n: number) => String(n), (n: number) => `${n} min`], notSet: "Not set", reasonsLabel: "Recommendation reasons", reasons: { interest: "Direct topic interest", identity: "Fits your role", goal: "Goal-related track", diversity: "Adds topic breadth", manual: "Manually kept in this route" }, buffer: (n: number) => `Schedule note: allow a suggested ${n}-minute buffer`, shareText: "Here is my WAIC 2026 visit route.", shareOpened: "Share sheet opened", copied: "Link copied", copyUnavailable: "Copy unavailable. Share from the address bar.", cancelled: "Sharing cancelled", shareFailed: "Sharing failed. Try again.", icsCreated: "ICS created", shareRoute: "Share route", downloadIcs: "Download ICS", startTime: (date: string) => `${date} start time`, endTime: (date: string) => `${date} end time`, rejections: { "outside-availability": "Outside your availability", "time-conflict": "Conflicts with a selected event", "venue-buffer": "Not enough venue-change buffer", "daily-limit": "Daily event limit reached", "lower-match": "Replaced by a better-matching combination" }, removeFromRoute: "Remove from route" },
  ja: { hour: (n: number) => `${n}時間`, attention: "ルートの集中力予算", metricLabels: ["イベント数", "有効コンテンツ時間", "目的テーマの網羅率", "テーマ数", "会場移動", "推奨バッファ"], metricValues: [(n: number) => `${n}件`, (n: number) => `${n}テーマ`, (n: number) => `${n}回`, (n: number) => `${n}分`], notSet: "未設定", reasonsLabel: "推薦理由", reasons: { interest: "関心テーマに一致", identity: "役割に適合", goal: "目的に関連", diversity: "テーマの幅を追加", manual: "手動で保持" }, buffer: (n: number) => `移動の目安：${n}分の余裕を推奨`, shareText: "私のWAIC 2026来場ルートです。", shareOpened: "共有画面を開きました", copied: "リンクをコピーしました", copyUnavailable: "コピーできません。アドレスバーから共有してください。", cancelled: "共有をキャンセルしました", shareFailed: "共有に失敗しました", icsCreated: "ICSを作成しました", shareRoute: "ルートを共有", downloadIcs: "ICSをダウンロード", startTime: (date: string) => `${date}の開始時刻`, endTime: (date: string) => `${date}の終了時刻`, rejections: { "outside-availability": "参加可能時間外", "time-conflict": "選択済みイベントと重複", "venue-buffer": "会場移動時間が不足", "daily-limit": "1日の件数上限", "lower-match": "より適した組み合わせを優先" }, removeFromRoute: "ルートから削除" },
  ko: { hour: (n: number) => `${n}시간`, attention: "동선 집중도 예산", metricLabels: ["행사 수", "유효 콘텐츠 시간", "목표 주제 범위", "주제 수", "장소 이동", "권장 여유 시간"], metricValues: [(n: number) => `${n}개`, (n: number) => `${n}개`, (n: number) => `${n}회`, (n: number) => `${n}분`], notSet: "미설정", reasonsLabel: "추천 이유", reasons: { interest: "관심 주제 일치", identity: "역할에 적합", goal: "목표와 관련", diversity: "주제 폭 확대", manual: "수동 유지" }, buffer: (n: number) => `연결 안내: ${n}분 여유 권장`, shareText: "나의 WAIC 2026 방문 동선입니다.", shareOpened: "공유 창을 열었습니다", copied: "링크를 복사했습니다", copyUnavailable: "복사할 수 없습니다. 주소창에서 공유하세요.", cancelled: "공유를 취소했습니다", shareFailed: "공유에 실패했습니다", icsCreated: "ICS를 만들었습니다", shareRoute: "동선 공유", downloadIcs: "ICS 다운로드", startTime: (date: string) => `${date} 시작 시간`, endTime: (date: string) => `${date} 종료 시간`, rejections: { "outside-availability": "가능한 시간 밖", "time-conflict": "선택한 행사와 충돌", "venue-buffer": "장소 이동 여유 부족", "daily-limit": "일일 행사 한도 도달", "lower-match": "더 적합한 조합을 우선" }, removeFromRoute: "동선에서 제거" },
  fr: { hour: (n: number) => `${n} h`, attention: "Budget d’attention du parcours", metricLabels: ["Événements", "Heures de contenu", "Couverture des objectifs", "Thèmes", "Changements de lieu", "Marge conseillée"], metricValues: [(n: number) => String(n), (n: number) => String(n), (n: number) => String(n), (n: number) => `${n} min`], notSet: "Non défini", reasonsLabel: "Motifs de recommandation", reasons: { interest: "Intérêt direct", identity: "Adapté à votre rôle", goal: "Lié à vos objectifs", diversity: "Élargit les thèmes", manual: "Conservé manuellement" }, buffer: (n: number) => `Prévoir une marge de ${n} min`, shareText: "Voici mon parcours WAIC 2026.", shareOpened: "Fenêtre de partage ouverte", copied: "Lien copié", copyUnavailable: "Copie impossible. Partagez depuis la barre d’adresse.", cancelled: "Partage annulé", shareFailed: "Échec du partage", icsCreated: "Fichier ICS créé", shareRoute: "Partager le parcours", downloadIcs: "Télécharger l’ICS", startTime: (date: string) => `Heure de début du ${date}`, endTime: (date: string) => `Heure de fin du ${date}`, rejections: { "outside-availability": "Hors de vos disponibilités", "time-conflict": "Conflit avec un événement sélectionné", "venue-buffer": "Marge de déplacement insuffisante", "daily-limit": "Limite quotidienne atteinte", "lower-match": "Remplacé par une meilleure combinaison" }, removeFromRoute: "Retirer du parcours" },
  de: { hour: (n: number) => `${n} Std.`, attention: "Aufmerksamkeitsbudget der Route", metricLabels: ["Veranstaltungen", "Inhaltsstunden", "Zielabdeckung", "Themen", "Ortswechsel", "Empfohlener Puffer"], metricValues: [(n: number) => String(n), (n: number) => String(n), (n: number) => String(n), (n: number) => `${n} Min.`], notSet: "Nicht festgelegt", reasonsLabel: "Empfehlungsgründe", reasons: { interest: "Direktes Interesse", identity: "Passt zu Ihrer Rolle", goal: "Zielbezogen", diversity: "Erweitert Themenbreite", manual: "Manuell beibehalten" }, buffer: (n: number) => `${n} Min. Puffer einplanen`, shareText: "Hier ist meine WAIC-2026-Besuchsroute.", shareOpened: "Teilen-Dialog geöffnet", copied: "Link kopiert", copyUnavailable: "Kopieren nicht möglich. Über die Adressleiste teilen.", cancelled: "Teilen abgebrochen", shareFailed: "Teilen fehlgeschlagen", icsCreated: "ICS erstellt", shareRoute: "Route teilen", downloadIcs: "ICS herunterladen", startTime: (date: string) => `Startzeit am ${date}`, endTime: (date: string) => `Endzeit am ${date}`, rejections: { "outside-availability": "Außerhalb Ihrer Verfügbarkeit", "time-conflict": "Konflikt mit ausgewählter Veranstaltung", "venue-buffer": "Zu wenig Wechselpuffer", "daily-limit": "Tageslimit erreicht", "lower-match": "Durch bessere Kombination ersetzt" }, removeFromRoute: "Aus Route entfernen" },
  es: { hour: (n: number) => `${n} h`, attention: "Presupuesto de atención de la ruta", metricLabels: ["Actividades", "Horas de contenido", "Cobertura de objetivos", "Temas", "Cambios de recinto", "Margen recomendado"], metricValues: [(n: number) => String(n), (n: number) => String(n), (n: number) => String(n), (n: number) => `${n} min`], notSet: "Sin definir", reasonsLabel: "Motivos de recomendación", reasons: { interest: "Interés directo", identity: "Encaja con tu perfil", goal: "Relacionado con el objetivo", diversity: "Amplía los temas", manual: "Conservado manualmente" }, buffer: (n: number) => `Deja un margen de ${n} min`, shareText: "Esta es mi ruta WAIC 2026.", shareOpened: "Se abrió el panel para compartir", copied: "Enlace copiado", copyUnavailable: "No se pudo copiar. Comparte desde la barra de direcciones.", cancelled: "Uso compartido cancelado", shareFailed: "Error al compartir", icsCreated: "ICS creado", shareRoute: "Compartir ruta", downloadIcs: "Descargar ICS", startTime: (date: string) => `Hora de inicio del ${date}`, endTime: (date: string) => `Hora de fin del ${date}`, rejections: { "outside-availability": "Fuera de tu disponibilidad", "time-conflict": "Coincide con una actividad elegida", "venue-buffer": "Margen de traslado insuficiente", "daily-limit": "Límite diario alcanzado", "lower-match": "Sustituida por una combinación mejor" }, removeFromRoute: "Quitar de la ruta" },
  ar: { hour: (n: number) => `${n} ساعة`, attention: "ميزانية الانتباه للمسار", metricLabels: ["الفعاليات", "ساعات المحتوى", "تغطية الأهداف", "الموضوعات", "تغييرات المكان", "الهامش المقترح"], metricValues: [(n: number) => `${n}`, (n: number) => `${n}`, (n: number) => `${n}`, (n: number) => `${n} دقيقة`], notSet: "غير محدد", reasonsLabel: "أسباب التوصية", reasons: { interest: "اهتمام مباشر", identity: "يناسب دورك", goal: "مرتبط بالهدف", diversity: "يوسع الموضوعات", manual: "تم الاحتفاظ به يدوياً" }, buffer: (n: number) => `اترك هامشاً قدره ${n} دقيقة`, shareText: "هذا مسار زيارتي إلى WAIC 2026.", shareOpened: "تم فتح نافذة المشاركة", copied: "تم نسخ الرابط", copyUnavailable: "تعذر النسخ. شارك من شريط العنوان.", cancelled: "ألغيت المشاركة", shareFailed: "فشلت المشاركة", icsCreated: "تم إنشاء ICS", shareRoute: "مشاركة المسار", downloadIcs: "تنزيل ICS", startTime: (date: string) => `وقت بدء ${date}`, endTime: (date: string) => `وقت انتهاء ${date}`, rejections: { "outside-availability": "خارج وقتك المتاح", "time-conflict": "يتعارض مع فعالية مختارة", "venue-buffer": "هامش التنقل غير كافٍ", "daily-limit": "تم بلوغ الحد اليومي", "lower-match": "استبدل بمزيج أكثر ملاءمة" }, removeFromRoute: "إزالة من المسار" },
});
